apiVersion: kro.run/v1alpha1
kind: ResourceGroup
metadata:
  name: cel-foreach-error
spec:
  schema:
    apiVersion: v1alpha1
    kind: TestCELForEachError
    spec:
      items:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            value:
              type: integer
  resources:
    - id: configmaps
      forEach:
        # This will cause a divide by zero at runtime
        - ${schema.spec.items.map(item, {"name": item.name, "divideByZero": item.value / 0})}
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: ${forEach.name}
      data:
        result: ${forEach.divideByZero}
