package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "Usage: %s <min-version> [max-version]\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "Example: %s 1.28 1.31\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "Example: %s 1.28      (max auto-detected)\n", os.Args[0])
		os.Exit(1)
	}

	minVer, err := parseVersion(os.Args[1])
	if err != nil {
		fmt.Fprintf(os.Stderr, "Invalid min version: %v\n", err)
		os.Exit(1)
	}

	var maxVer int
	if len(os.Args) >= 3 {
		// Max version explicitly provided
		maxVer, err = parseVersion(os.Args[2])
		if err != nil {
			fmt.Fprintf(os.Stderr, "Invalid max version: %v\n", err)
			os.Exit(1)
		}
	} else {
		// Auto-detect latest version
		fmt.Println("Auto-detecting latest Kubernetes version...")
		maxVer, err = detectLatestVersion()
		if err != nil {
			fmt.Fprintf(os.Stderr, "Failed to detect latest version: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("Detected latest version: 1.%d\n", maxVer)
	}

	if minVer > maxVer {
		fmt.Fprintf(os.Stderr, "Min version must be <= max version\n")
		os.Exit(1)
	}

	// Ensure schemas directory exists
	schemasDir := filepath.Join("..", "schemas")
	if err := os.MkdirAll(schemasDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to create schemas directory: %v\n", err)
		os.Exit(1)
	}

	// Initialize go.mod if it doesn't exist
	if _, err := os.Stat("go.mod"); os.IsNotExist(err) {
		cmd := exec.Command("go", "mod", "init", "generator")
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to init module: %v\n", err)
			os.Exit(1)
		}
	}

	// Generate schemas for all versions in range
	var generatedVersions []string
	for ver := minVer; ver <= maxVer; ver++ {
		userVersion := fmt.Sprintf("v1.%d", ver)
		moduleVersion := fmt.Sprintf("v0.%d.0", ver)

		if err := generateSchema(userVersion, moduleVersion); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to generate %s: %v\n", userVersion, err)
			os.Exit(1)
		}
		generatedVersions = append(generatedVersions, userVersion)
	}

	// Generate schemas.go file
	if err := generateSchemasFile(generatedVersions); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to generate schemas.go: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("\n✓ All schemas generated successfully!\n")
	fmt.Printf("✓ Generated schemas.go with %d embedded schemas\n", len(generatedVersions))
}

func parseVersion(v string) (int, error) {
	// Handle "1.28" or "v1.28"
	v = strings.TrimPrefix(v, "v")
	parts := strings.Split(v, ".")
	if len(parts) != 2 || parts[0] != "1" {
		return 0, fmt.Errorf("version must be in format 1.X or v1.X")
	}
	return strconv.Atoi(parts[1])
}

func detectLatestVersion() (int, error) {
	// Query available versions from k8s.io/apiextensions-apiserver
	cmd := exec.Command("go", "list", "-m", "-versions", "k8s.io/apiextensions-apiserver")
	var out bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return 0, fmt.Errorf("failed to list versions: %w", err)
	}

	// Parse output: "k8s.io/apiextensions-apiserver v0.28.0 v0.29.0 v0.30.0 v0.31.0 ..."
	// Only match stable versions (v0.X.0, not v0.X.Y or alpha/beta/rc)
	output := out.String()
	re := regexp.MustCompile(`v0\.(\d+)\.0(?:\s|$)`)
	matches := re.FindAllStringSubmatch(output, -1)

	if len(matches) == 0 {
		return 0, fmt.Errorf("no stable versions found")
	}

	// Find the highest minor version
	maxMinor := 0
	for _, match := range matches {
		if len(match) < 2 {
			continue
		}
		minor, err := strconv.Atoi(match[1])
		if err != nil {
			continue
		}
		if minor > maxMinor {
			maxMinor = minor
		}
	}

	if maxMinor == 0 {
		return 0, fmt.Errorf("failed to parse versions")
	}

	return maxMinor, nil
}

func generateSchema(userVersion, moduleVersion string) error {
	fmt.Printf("Generating schema for %s (module %s)...\n", userVersion, moduleVersion)

	// Update go.mod with specific version
	cmd := exec.Command("go", "get", fmt.Sprintf("k8s.io/apiextensions-apiserver@%s", moduleVersion))
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("go get failed: %w", err)
	}

	// Tidy dependencies
	cmd = exec.Command("go", "mod", "tidy")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("go mod tidy failed: %w", err)
	}

	// Extract schema
	cmd = exec.Command("go", "run", "extractor.go", userVersion)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("extractor failed: %w", err)
	}

	return nil
}

func generateSchemasFile(versions []string) error {
	var sb strings.Builder

	sb.WriteString(`// Code generated by go generate; DO NOT EDIT.
// Generated schemas for Kubernetes versions ` + versions[0] + ` to ` + versions[len(versions)-1] + `

package schemas

import _ "embed"

`)

	// Generate embed directives and variables
	for _, ver := range versions {
		varName := strings.ReplaceAll(ver, ".", "")
		sb.WriteString(fmt.Sprintf("//go:embed schemas_%s.json\n", ver))
		sb.WriteString(fmt.Sprintf("var schemas%s []byte\n\n", varName))
	}

	// Generate version map
	sb.WriteString("// Schemas maps Kubernetes versions to their embedded OpenAPI schemas\n")
	sb.WriteString("var Schemas = map[string][]byte{\n")
	for _, ver := range versions {
		varName := strings.ReplaceAll(ver, ".", "")
		sb.WriteString(fmt.Sprintf("\t%q: schemas%s,\n", ver, varName))
	}
	sb.WriteString("}\n")

	// Write to file
	outFile := filepath.Join("..", "schemas", "schemas.go")
	if err := os.WriteFile(outFile, []byte(sb.String()), 0644); err != nil {
		return err
	}

	fmt.Printf("  ✓ Generated %s\n", outFile)
	return nil
}
