// Copyright 2025 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package analysis

// K8sFieldDocs provides documentation for common Kubernetes fields
var K8sFieldDocs = map[string]string{
	"metadata": "Standard object metadata. Includes name, namespace, labels, and annotations.",
	"metadata.name": "Name must be unique within a namespace. Required when creating resources.",
	"metadata.namespace": "Namespace defines the space within which the name must be unique. Default is 'default'.",
	"metadata.labels": "Map of string keys and values for organizing and selecting objects. Labels can be used with selectors.",
	"metadata.annotations": "Arbitrary non-identifying metadata. Can store tool-specific configuration.",
	"metadata.creationTimestamp": "Server-populated timestamp of when this object was created.",
	"metadata.deletionTimestamp": "Set when an object is being deleted. Used with finalizers.",
	"metadata.generation": "Incremented by the system on spec updates. Used for optimistic concurrency.",
	"metadata.resourceVersion": "Opaque version string used for optimistic concurrency control.",
	"metadata.uid": "Unique ID in time and space. Generated by the server.",
	"metadata.finalizers": "List of finalizers that must be cleared before the object is deleted.",
	"metadata.ownerReferences": "List of objects that own this object. If all owners are deleted, this object will be garbage collected.",

	"spec": "Specification of the desired behavior of the resource.",
	"status": "Most recently observed status of the resource. Populated by the system. Read-only.",

	// Deployment
	"spec.replicas": "Number of desired pods. Defaults to 1.",
	"spec.selector": "Label selector for pods. Must match template metadata labels.",
	"spec.template": "Template describes the pods that will be created.",
	"spec.strategy": "Deployment strategy to use when replacing existing pods with new ones.",
	"spec.minReadySeconds": "Minimum number of seconds for which a newly created pod should be ready.",
	"spec.revisionHistoryLimit": "Number of old ReplicaSets to retain for rollback. Defaults to 10.",
	"spec.paused": "Indicates that the deployment is paused.",
	"spec.progressDeadlineSeconds": "Maximum time in seconds for a deployment to make progress. Defaults to 600.",

	"spec.selector.matchLabels": "Map of key-value pairs. A pod must match all labels to be selected.",
	"spec.selector.matchExpressions": "List of label selector requirements. More flexible than matchLabels.",

	"spec.template.metadata": "Metadata for the pod template. Labels here must match spec.selector.",
	"spec.template.spec": "Specification of the desired behavior of the pod.",
	"spec.template.spec.containers": "List of containers belonging to the pod. At least one container is required.",
	"spec.template.spec.volumes": "List of volumes that can be mounted by containers.",
	"spec.template.spec.restartPolicy": "Restart policy for all containers. One of Always, OnFailure, Never. Defaults to Always.",
	"spec.template.spec.serviceAccountName": "Name of the ServiceAccount to use to run this pod.",
	"spec.template.spec.nodeName": "Request to schedule this pod onto a specific node.",
	"spec.template.spec.nodeSelector": "Selector which must match a node's labels for the pod to be scheduled on that node.",
	"spec.template.spec.affinity": "Advanced scheduling constraints. Allows expressing node/pod affinity and anti-affinity.",
	"spec.template.spec.tolerations": "List of tolerations. Allows pods to schedule onto nodes with matching taints.",

	// Service
	"spec.type": "Type of Service. One of ClusterIP, NodePort, LoadBalancer, ExternalName. Defaults to ClusterIP.",
	"spec.ports": "List of ports exposed by this service.",
	"spec.clusterIP": "IP address of the service. Usually assigned automatically.",
	"spec.externalIPs": "List of IP addresses for which nodes will accept traffic for this service.",
	"spec.sessionAffinity": "Enable client IP based session affinity. One of None, ClientIP. Defaults to None.",
	"spec.loadBalancerIP": "Deprecated. Request a specific IP for the load balancer.",
	"spec.loadBalancerSourceRanges": "Traffic from these IP ranges will be allowed to the load balancer.",
	"spec.externalName": "External reference that this service points to. Used with type ExternalName.",
	"spec.externalTrafficPolicy": "How external traffic is routed. One of Local, Cluster. Defaults to Cluster.",
	"spec.healthCheckNodePort": "Port for health checking when externalTrafficPolicy is Local.",
	"spec.publishNotReadyAddresses": "Allow endpoints to be published before pods are ready.",

	// ConfigMap
	"data": "Data contains the configuration data. Keys must be valid DNS subdomain names.",
	"binaryData": "BinaryData contains binary data. Values are base64 encoded.",

	// Secret
	"type": "Type of secret. Used to facilitate programmatic handling. Opaque is the default.",
	"stringData": "Convenience field for string data. Will be converted to base64 in data field.",

	// PersistentVolumeClaim
	"spec.accessModes": "Access modes for the volume. One or more of ReadWriteOnce, ReadOnlyMany, ReadWriteMany.",
	"spec.resources": "Minimum resources the volume should have.",
	"spec.storageClassName": "Name of the StorageClass required by the claim.",
	"spec.volumeMode": "What type of volume is required. One of Filesystem, Block. Defaults to Filesystem.",
	"spec.volumeName": "Binding to a specific PersistentVolume.",
}

// GetFieldDocs returns documentation for a Kubernetes field path
func GetFieldDocs(fieldPath string) string {
	if doc, ok := K8sFieldDocs[fieldPath]; ok {
		return doc
	}
	return ""
}
