// Code generated by go generate; DO NOT EDIT.
// Generated schemas for Kubernetes versions v1.28 to v1.36

package schemas

import _ "embed"

//go:embed schemas_v1.28.json
var schemasv128 []byte

//go:embed schemas_v1.29.json
var schemasv129 []byte

//go:embed schemas_v1.30.json
var schemasv130 []byte

//go:embed schemas_v1.31.json
var schemasv131 []byte

//go:embed schemas_v1.32.json
var schemasv132 []byte

//go:embed schemas_v1.33.json
var schemasv133 []byte

//go:embed schemas_v1.34.json
var schemasv134 []byte

//go:embed schemas_v1.35.json
var schemasv135 []byte

//go:embed schemas_v1.36.json
var schemasv136 []byte

// Schemas maps Kubernetes versions to their embedded OpenAPI schemas
var Schemas = map[string][]byte{
	"v1.28": schemasv128,
	"v1.29": schemasv129,
	"v1.30": schemasv130,
	"v1.31": schemasv131,
	"v1.32": schemasv132,
	"v1.33": schemasv133,
	"v1.34": schemasv134,
	"v1.35": schemasv135,
	"v1.36": schemasv136,
}
